services:
    IntProg\FeatureFlagBundle\EventListener\ConfigurationScopeListener:
        public: false
        arguments:
            - '@intprog.feature_flag.repository'
        tags:
            - { name: kernel.event_subscriber }
