services:
    IntProg\FeatureFlagBundle\EventListener\ConfigurationScopeListener:
        public: false
        arguments:
            - '@intprog.feature_flag.repository'
        tags:
            - { name: kernel.event_subscriber }

    IntProg\FeatureFlagBundle\EventListener\BuildSchemaListener:
        public: false
        arguments:
            - '@=service("kernel").locateResource("@IntProgFeatureFlagBundle/Resources/schema/doctrine.yaml")'
        tags:
            - { name: kernel.event_subscriber }

    IntProg\FeatureFlagBundle\EventListener\AdminFeatureFlagTabListener:
        public: false
        calls:
            - ['setAuthorizationChecker', ['@security.authorization_checker']]
            - ['setTranslator', ['@translator']]
            - ['setFactory', ['@knp_menu.factory']]
        tags:
            - { name: kernel.event_subscriber }

    IntProg\FeatureFlagBundle\EventListener\FeatureFlagEventsSubscriber:
        public: false
        arguments:
            - '@ezplatform.http_cache.purge_client'
        tags:
            - { name: kernel.event_subscriber }
