intprog_featureFlag_dashboard:
    path: /feature-flag/dashboard
    methods:
        - GET
    defaults:
        _controller: intprog_featureFlagDashboardController:dashboard

intprog_featureFlag.admin_ui.rest:
    resource: '@IntProgFeatureFlagBundle/Resources/config/routing_rest.yml'
    prefix: '%ezpublish_rest.path_prefix%'
