services:
    intprog.repository.service.inner_feature_flag:
        class: IntProg\FeatureFlagBundle\Core\Repository\FeatureFlagService
        public: true
        arguments:
            - '@IntProg\FeatureFlagBundle\Core\Persistence\Cache\Handler'
            - '@translator'
            - '@eZ\Publish\Core\Repository\Permission\PermissionResolver'
            - '%intprog.feature.flag.feature_list%'
            -
    intprog.repository.service.event_feature_flag:
        class: IntProg\FeatureFlagBundle\Core\Event\FeatureFlagService
        public: true
        arguments:
            - '@intprog.repository.service.inner_feature_flag'
            - '@event_dispatcher'

    intprog.repository.service.feature_flag:
        alias: 'intprog.repository.service.event_feature_flag'

    intprog.feature_flag.repository:
        class: IntProg\FeatureFlagBundle\Services\FeatureFlagRepository
        public: true
        arguments:
            - '@intprog.repository.service.feature_flag'
            - '@translator.default'
            - '@ezplatform.view_cache.response_tagger.dispatcher'
            - '%intprog.feature.flag.feature_list%'
            - '%ezpublish.siteaccess.list%'
            - '%ezpublish.siteaccess.groups_by_siteaccess%'
            - '%kernel.debug%'
        calls:
            - ['setSiteAccess', ['@ezpublish.siteaccess']]

    intprog.api.role.limitation_type.configuration_scope:
        class: IntProg\FeatureFlagBundle\Core\Limitation\ConfigurationScopeLimitationType
        tags:
            - {name: ezpublish.limitationType, alias: ConfigurationScope}

    # controller definitions
    intprog.feature_flag_operation.controller:
        class: IntProg\FeatureFlagBundle\Controller\FeatureFlagOperationController
        autowire: true
        lazy: true
        arguments:
            - '@security.authorization_checker'
            - '@intprog.feature_flag.repository'
            - '@intprog.repository.service.feature_flag'
            - '%intprog.feature.flag.feature_list%'
        tags:
            - { name: controller.service_arguments }
